"""
Shared domain enumerations used across the AuraRisk platform.

These values correspond to the business concepts defined during Phase 0.

Keeping them in one place prevents inconsistent strings across:

- API contracts.
- Model services.
- Agent workflows.
- Approval policies.
- Database records.
- Evaluation pipelines.
"""

from enum import StrEnum


class CaseCategory(StrEnum):
    """
    Main business category associated with an investigation.

    StrEnum keeps the values compatible with JSON, Pydantic models,
    database records, and existing YAML configuration.
    """

    FRAUD = "FRAUD"
    CREDIT_RISK = "CREDIT_RISK"
    TRANSACTION_MONITORING = "TRANSACTION_MONITORING"
    POLICY_COMPLIANCE = "POLICY_COMPLIANCE"
    MIXED_SIGNAL = "MIXED_SIGNAL"


class CaseSeverity(StrEnum):
    """Relative urgency assigned to an investigation."""

    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class CaseStatus(StrEnum):
    """
    States in the AuraRisk case lifecycle.

    Later, the workflow engine will restrict which transitions are valid.
    """

    CREATED = "CREATED"
    DATA_COLLECTION = "DATA_COLLECTION"
    SPECIALIST_ANALYSIS = "SPECIALIST_ANALYSIS"
    SYNTHESIS = "SYNTHESIS"
    VALIDATION = "VALIDATION"
    AWAITING_APPROVAL = "AWAITING_APPROVAL"
    COMPLETED = "COMPLETED"
    REJECTED = "REJECTED"
    FAILED = "FAILED"


class EvidenceClassification(StrEnum):
    """
    Classify statements according to how they were produced.

    This distinction prevents a model prediction or LLM-generated hypothesis
    from being presented as a directly verified fact.
    """

    FACT = "FACT"
    MODEL_OUTPUT = "MODEL_OUTPUT"
    POLICY = "POLICY"
    INFERENCE = "INFERENCE"
    RECOMMENDATION = "RECOMMENDATION"


class InvestigationOutcome(StrEnum):
    """
    Business-level outcomes generated by an investigation.

    These values correspond to the mappings in:

        config/policies/outcome_action_mapping.yaml
    """

    CLEAR_ALERT = "CLEAR_ALERT"
    CONTINUE_MONITORING = "CONTINUE_MONITORING"
    REQUEST_MORE_INFORMATION = "REQUEST_MORE_INFORMATION"

    ESCALATE_FRAUD_REVIEW = "ESCALATE_FRAUD_REVIEW"
    ESCALATE_CREDIT_REVIEW = "ESCALATE_CREDIT_REVIEW"
    ESCALATE_POLICY_REVIEW = "ESCALATE_POLICY_REVIEW"

    RECOMMEND_ACCOUNT_HOLD = "RECOMMEND_ACCOUNT_HOLD"
    RECOMMEND_CUSTOMER_VERIFICATION = "RECOMMEND_CUSTOMER_VERIFICATION"
    RECOMMEND_REPAYMENT_OUTREACH = "RECOMMEND_REPAYMENT_OUTREACH"


class UserRole(StrEnum):
    """
    User and service roles recognized by the approval policy.

    Values intentionally match the role identifiers defined in:

        config/policies/action_approval_policy.yaml
    """

    SYSTEM_AGENT = "system_agent"
    FRAUD_ANALYST = "fraud_analyst"
    CREDIT_RISK_ANALYST = "credit_risk_analyst"
    INVESTIGATION_SUPERVISOR = "investigation_supervisor"
    COMPLIANCE_REVIEWER = "compliance_reviewer"
    PLATFORM_ADMINISTRATOR = "platform_administrator"
    AUDITOR = "auditor"


class ActionRiskLevel(StrEnum):
    """
    Risk classification used by deterministic action policies.

    These values will determine whether an action can execute immediately,
    requires approval, or must always be rejected.
    """

    READ_ONLY = "READ_ONLY"
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"
    PROHIBITED = "PROHIBITED"


class ApprovalDecision(StrEnum):
    """Decision recorded by an authorized human reviewer."""

    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class ValidationStatus(StrEnum):
    """Outcome of the deterministic investigation validation stage."""

    PENDING = "PENDING"
    PASSED = "PASSED"
    FAILED = "FAILED"
